class_name IconCatalog
extends RefCounted
## Generated by tools/build_brand_assets.py. Semantic glyphs and original card art.

const IDS: Array[StringName] = [
	&"ball",
	&"hole",
	&"stroke",
	&"par",
	&"trajectory",
	&"power",
	&"tee",
	&"timer",
	&"coin",
	&"biome",
	&"benefit",
	&"curse",
	&"stack",
	&"card",
	&"active_effect",
	&"shop",
	&"lock",
	&"warning",
	&"oob",
	&"sand",
	&"water",
	&"ice",
	&"lava",
	&"bounce_pad",
	&"blocker",
	&"pendulum",
	&"falling_ice",
	&"meadow",
	&"desert",
	&"autumn",
	&"snow",
	&"swamp",
	&"volcanic",
	&"settings",
	&"display",
	&"audio",
	&"controls",
	&"accessibility",
	&"back",
	&"continue",
	&"close",
	&"restart",
	&"copy",
	&"seed",
	&"randomize",
	&"difficulty_easy",
	&"difficulty_normal",
	&"difficulty_hard",
	&"dark",
	&"light",
	&"menu",
	&"help",
	&"quit",
	&"chevron_down",
	&"chevron_up",
	&"check",
	&"trophy",
	&"star",
	&"rarity_common",
	&"rarity_rare",
	&"rarity_epic",
	&"rarity_legendary",
	&"power_club",
	&"overdrive_driver",
	&"rangefinder_lens",
	&"coin_magnet",
	&"sand_cleats",
	&"heavy_core",
	&"gust_guard",
	&"lucky_putter",
	&"missing",
]
const ALIASES := {
	&"strokes": &"stroke",
	&"club": &"stroke",
	&"coins": &"coin",
	&"bonus": &"benefit",
	&"cards": &"card",
	&"control": &"trajectory",
	&"target": &"rangefinder_lens",
	&"difficulty": &"difficulty_normal",
	&"tutorial": &"help",
	&"score_good": &"star",
	&"score_bad": &"curse",
	&"replay": &"restart",
	&"wall": &"blocker",
	&"moving_hazard": &"pendulum",
	&"spike_ball": &"pendulum",
	&"copy_seed": &"copy",
	&"risk": &"warning",
	&"reward": &"star",
}
const ROOT := "res://assets/ui/icons/"
const CARD_ROOT := "res://assets/presentation/cards/"
const CARD_IDS: Array[StringName] = [
	&"overdrive_driver", &"rangefinder_lens", &"sand_cleats", &"heavy_core",
	&"lucky_putter", &"power_club", &"coin_magnet", &"gust_guard",
]
const CARD_ALIASES := {
	&"tutorial_training_driver": &"overdrive_driver",
	&"tutorial_sand_shoes": &"sand_cleats",
	&"tutorial_pocket_change": &"coin_magnet",
	&"tutorial_steady_grip": &"rangefinder_lens",
}
static var _card_textures: Dictionary = {}

static func canonical(id: StringName) -> StringName:
	return CARD_ALIASES.get(id, ALIASES.get(id, id))

static func has_icon(id: StringName) -> bool:
	return canonical(id) in IDS

static func asset_path(id: StringName, small := false) -> String:
	var resolved := canonical(id)
	if has_card_art(resolved):
		return card_asset_path(resolved)
	if resolved not in IDS:
		resolved = &"missing"
	return ROOT + "icon_%s%s.svg" % [resolved, "_small" if small else ""]

static func texture(id: StringName, small := false) -> Texture2D:
	if has_card_art(id):
		return card_texture(id)
	# The drawing control retains this reference for the lifetime of its draw RID.
	return load(asset_path(id, small)) as Texture2D

static func has_card_art(id: StringName) -> bool:
	return canonical(id) in CARD_IDS

static func card_asset_path(id: StringName) -> String:
	var resolved := canonical(id)
	return CARD_ROOT + String(resolved) + ".png" if resolved in CARD_IDS else ""

static func card_texture(id: StringName) -> Texture2D:
	var resolved := canonical(id)
	if resolved not in CARD_IDS:
		return null
	# ResourceLoader caches weakly. Keep a bounded strong reference to each of the
	# eight sprites so a texture loaded in _draw survives until the renderer uses it.
	if not _card_textures.has(resolved):
		var loaded := load(card_asset_path(resolved)) as Texture2D
		if loaded:
			_card_textures[resolved] = loaded
	return _card_textures.get(resolved) as Texture2D
